# Generated by Django 5.1.7 on 2025-04-11 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldOfStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='field_of_study',
        ),
        migrations.AlterField(
            model_name='hotdoguser',
            name='field_of_study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.fieldofstudy'),
        ),
        migrations.AddField(
            model_name='course',
            name='field_of_study',
            field=models.ManyToManyField(blank=True, null=True, related_name='courses', to='core.fieldofstudy'),
        ),
    ]
