# Generated by Django 5.1.7 on 2025-04-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fieldofstudy_remove_course_field_of_study_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotdoguser',
            name='telegram_user_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
