# Generated by Django 5.1.4 on 2024-12-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_groupmeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tel_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
