# Generated by Django 5.1.7 on 2025-04-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fieldofstudy_remove_course_field_of_study_and_more'),
        ('task', '0002_task_is_finished_taskhistory_got_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='fields_of_study',
            field=models.ManyToManyField(blank=True, null=True, related_name='tasks', to='core.fieldofstudy'),
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='pre_fields_of_study',
            field=models.ManyToManyField(blank=True, null=True, related_name='task_history', to='core.fieldofstudy'),
        ),
    ]
