# Generated by Django 5.1.7 on 2025-04-11 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_task_fields_of_study_taskhistory_pre_fields_of_study'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
    ]
